# Generated by Django 5.2.14 on 2026-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0022_remove_ausencia_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencarelogio',
            name='origem_report',
            field=models.BooleanField(default=False, verbose_name='Origem Relatório'),
        ),
        migrations.AlterField(
            model_name='testepromocao',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Anexo da Folha de Teste'),
        ),
    ]
