# Generated by Django 5.2.14 on 2026-08-14 11:11

import colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0023_presencarelogio_origem_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testepromocao',
            name='anexo',
            field=models.FileField(blank=True, null=True, storage=colaboradores.models.testes_storage, upload_to='', verbose_name='Anexo da Folha de Teste'),
        ),
    ]
