# Generated by Django 5.2.14 on 2026-08-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0023_presencarelogio_origem_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='aviso_indenizado_dias',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dias Aviso Indenizado'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ferias_aviso_dias',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dias Férias Aviso'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ferias_proporcionais_dias',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dias Férias Proporcionais'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ferias_vencidas_dias',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Dias Férias Vencidas'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario_rescisao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário na Rescisão'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='valor_rescisao_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Estimado Rescisão'),
        ),
    ]
