# Generated by Django 5.2.14 on 2026-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0024_colaborador_aviso_indenizado_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacaoteste',
            name='acao',
            field=models.CharField(choices=[('ativar', 'Aprovar/Ativar'), ('registrar_resposta', 'Registrar Resposta do Supervisor'), ('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar'), ('pagar_premio_cancelar', 'Pagar Prêmio e Cancelar'), ('alterar_data_inicio', 'Alteração de Data de Início')], max_length=30, verbose_name='Ação'),
        ),
    ]
