# Generated by Django 5.2.14 on 2026-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0024_alter_testepromocao_anexo'),
        ('colaboradores', '0025_alter_historicoacaoteste_acao'),
    ]

    operations = [
    ]
