# Generated by Django 5.2.14 on 2026-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0032_loja_latitude_loja_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='geovictoria_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização GeoVictoria'),
        ),
    ]
