# Generated by Django 5.2.14 on 2026-08-28 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0033_loja_geovictoria_sincronizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumofolhamensal',
            name='valor_verbas_extraordinarias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor verbas extraordinárias'),
        ),
    ]
