# Generated by Django 5.2.14 on 2026-09-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0034_resumofolhamensal_valor_verbas_extraordinarias'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadcountMensalLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('total_ativos', models.IntegerField(default=0, verbose_name='Total de Ativos (Força de Trabalho)')),
                ('fechado', models.BooleanField(db_index=True, default=False, verbose_name='Mês Fechado')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcounts_mensais', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Headcount Mensal da Loja',
                'verbose_name_plural': 'Headcounts Mensais das Lojas',
                'indexes': [models.Index(fields=['ano', 'mes'], name='lojas_headc_ano_60a0c0_idx'), models.Index(fields=['loja', 'ano', 'mes'], name='lojas_headc_loja_id_f05969_idx')],
                'constraints': [models.UniqueConstraint(fields=('loja', 'ano', 'mes'), name='unique_headcount_mensal_loja_ano_mes')],
            },
        ),
    ]
